Repository Yoyakso/COMKET_BE, pull requests merged in 2025-05, with the labels that each got.

#16 배포 #5
  .gitignore
  src/main/java/com/yoyakso/comket/member/MemberController.java
  src/main/java/com/yoyakso/comket/member/MemberService.java
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
  src/main/java/com/yoyakso/comket/util/JwtTokenProvider.java
  src/main/java/com/yoyakso/comket/workspace/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/WorkspaceRepository.java
  src/main/java/com/yoyakso/comket/workspace/WorkspaceService.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceInfoResponse.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceRegisterRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceRegisterResponse.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/entity/Workspace.java
  src/main/java/com/yoyakso/comket/workspace/enums/Visibility.java
  src/main/java/com/yoyakso/comket/workspaceMember/entity/WorkspaceMember.java
  src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
  src/main/resources/application.yml
  src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java
Labels: 🚀 Deploy

#18 배포 #6
  build.gradle
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#19 구글 로그인 API RequestParam value 명시
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java
Labels: 🪛 Refactor

#20 배포 #7
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java
  src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java
Labels: 🚀 Deploy

#22 배포 #8
  src/main/resources/application.yml
Labels: 🚀 Deploy

#24 프로젝트 개발
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/yoyakso/comket/member/MemberService.java
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberUpdateRequest.java
  src/main/java/com/yoyakso/comket/project/entity/Project.java
  src/main/java/com/yoyakso/comket/project/enums/ProjectState.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/entity/ProjectMember.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/workspace/WorkspaceRepository.java
  src/main/resources/application-oauth2.yml
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🏗️ Feature, 🪛 Refactor

#25 구글 redirect_uri 프론트 변경
  src/main/resources/application.yml
Labels: 🪛 Refactor, 🚀 Deploy

#26 배포 #9
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/yoyakso/comket/member/MemberService.java
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberUpdateRequest.java
  src/main/java/com/yoyakso/comket/project/entity/Project.java
  src/main/java/com/yoyakso/comket/project/enums/ProjectState.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/entity/ProjectMember.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/workspace/WorkspaceRepository.java
  src/main/resources/application-oauth2.yml
  src/main/resources/application.yml
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🚀 Deploy

#27 Update: cors 설정 추가
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🪛 Refactor

#28 배포 #10
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🚀 Deploy

#35 Fix : verifyNoMoreInteractions 무효
  src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java
Labels: 🐞 Bug Fix, 🛠️ Hot Fix

#39 클라이언트에서 redirect_uri를 받을 수 있도록 변경
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
  src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
  src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java
Labels: 🏗️ Update

#42 구글 로그인 미사용 api 제거
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
  src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
  src/main/resources/application.yml
  src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java
Labels: 🔑 Chore, 🪛 Refactor

#46 JwtTokenFilter 적용
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/jwt/JwtTokenFilter.java
  src/main/java/com/yoyakso/comket/jwt/JwtTokenProvider.java
  src/main/java/com/yoyakso/comket/member/controller/MemberController.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/util/JwtTokenProvider.java
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
Labels: 🏗️ Feature, 🪛 Refactor, 🏗️ Update

#47 WorkspaceController JwtTokenFilter 적용
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
Labels: 🏗️ Update

#49 Http Request Whitelist 누락 추가
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🐞 Bug Fix, 🛠️ Hot Fix

#50 배포 #14
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🚀 Deploy

#51 구글 로그인 - 회원가입 여부에 따라 Response 변경
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java
  src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java
Labels: 🏗️ Update

#52 배포 #15
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java
  src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java
Labels: 🚀 Deploy

#53 자체 로그인 구현
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleDetailRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleDetailResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleLoginResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleTokenRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleTokenResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/LoginRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
  src/main/java/com/yoyakso/comket/auth/service/AuthService.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/member/controller/MemberController.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleTokenRequest.java
  src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
  src/test/java/com/yoyakso/comket/auth/GoogleOAuth2ServiceTest.java
Labels: 🏗️ Feature

#54 배포 #16
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleDetailRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleDetailResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleLoginResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleTokenRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/GoogleTokenResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/LoginRequest.java
  src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
  src/main/java/com/yoyakso/comket/auth/service/AuthService.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/member/controller/MemberController.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
  src/main/java/com/yoyakso/comket/oauth2/dto/GoogleTokenRequest.java
  src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
  src/test/java/com/yoyakso/comket/auth/GoogleOAuth2ServiceTest.java
Labels: 🚀 Deploy

#55 fix : Workspace-Member 수정/삭제 관련 id->email 수정
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceMemberInfoUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
Labels: 🏗️ Update

#56 배포 #17
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceMemberInfoUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
Labels: 🚀 Deploy

#59 프로젝트 멤버 추가 / 프로젝트 전체 조회 이슈 수정
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/entity/ProjectMember.java
  src/main/java/com/yoyakso/comket/projectMember/enums/ProjectMemberState.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
Labels: 🏗️ Feature, 🐞 Bug Fix, 🏗️ Update

#61 프로젝트 태그 기능 개발 / 프로젝트 조회 Response 변경
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectOwnerTransferRequest.java
  src/main/java/com/yoyakso/comket/project/entity/Project.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🏗️ Feature, 🏗️ Update

#65 배포 #21
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectOwnerTransferRequest.java
  src/main/java/com/yoyakso/comket/project/entity/Project.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🚀 Deploy

#66 프로젝트 초대의 멤버 비교 버그 수정
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
Labels: 🛠️ Hot Fix

#67 배포 #22
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
Labels: 🚀 Deploy

#69 프로젝트 소유자일 경우 멤버 변경이 불가능한 이슈 해결
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
Labels: 🛠️ Hot Fix

#71 프로젝트Info 반환 시 adminId가 아니라 admin 정보 객체를 전달하도록 수정
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🏗️ Update

#70 배포 #23
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🛠️ Hot Fix, 🚀 Deploy

#68 Feat/ticket
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketCreateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketDeleteRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketStateUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketTypeUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/entity/Ticket.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketPriority.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketState.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketType.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🏗️ Feature

#72 배포 #24
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketCreateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketDeleteRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketStateUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketTypeUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/entity/Ticket.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketPriority.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketState.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketType.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🏗️ Feature, 🚀 Deploy

#76 배포 #26
  .github/workflows/aws.yml
  build.gradle
  docker-compose.yml
  install-kafka.sh
  src/main/java/com/yoyakso/comket/configuration/AsyncConfig.java
  src/main/java/com/yoyakso/comket/configuration/JacksonConfig.java
  src/main/java/com/yoyakso/comket/configuration/WebSocketConfig.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
  src/main/java/com/yoyakso/comket/thread/repository/ThreadMessageRepository.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaTopicService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
  src/main/java/com/yoyakso/comket/thread/util/JwtHandshakeInterceptor.java
  src/main/java/com/yoyakso/comket/thread/util/ThreadKafkaListenerManager.java
  src/main/java/com/yoyakso/comket/thread/util/ThreadMessageProducer.java
  src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#81 hotfix: install-kafka.sh 주석처리
  .github/workflows/aws.yml
Labels: 🛠️ Hot Fix

#83 hotfix: WS whitelist 추가 및 ticket 생성 시 kafka 로직 주석
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🛠️ Hot Fix

#84 배포 #29
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🚀 Deploy

#85 kafka용 ec2 연결
  .github/workflows/aws.yml
  docker-compose.yml
  install-kafka.sh
  src/main/java/com/yoyakso/comket/thread/util/JwtHandshakeInterceptor.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/resources/application.yml
Labels: 🏗️ Feature

#86 배포 #30
  .github/workflows/aws.yml
  docker-compose.yml
  install-kafka.sh
  src/main/java/com/yoyakso/comket/thread/util/JwtHandshakeInterceptor.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#87 프로젝트Id로 티켓Id를 가져오는 로직 수정
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🐞 Bug Fix

#88 배포 #31
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🚀 Deploy

#89 클라이언트 ping 요청 허용
  src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java
Labels: 🏗️ Feature

#90 배포 #32
  src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java
Labels: 🚀 Deploy

#97 프로젝트 전체 조회 API 수정
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
Labels: 🐞 Bug Fix

#99 테스트코드 수정
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🐞 Bug Fix

#100 배포 #37
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🚀 Deploy

#101 bugfix : 멤버 추가 중복 검사 로직 버그 수정
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
Labels: 🐞 Bug Fix

#102 배포 #38
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
Labels: 🚀 Deploy

#107 CD 파이프라인 시크릿 입력 오타 제거
  .github/workflows/aws.yml
Labels: 🐞 Bug Fix

#109 Feat/ticket-template
  src/main/java/com/yoyakso/comket/ticket/converter/AdditionalInfoConverter.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketCreateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/entity/Ticket.java
  src/main/java/com/yoyakso/comket/ticket/enums/TicketType.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
Labels: 🏗️ Feature

#111 요약 및 액션아이템 히스토리 불러오기 API 개발
  src/main/java/com/yoyakso/comket/ai/controller/AiController.java
  src/main/java/com/yoyakso/comket/ai/dto/ActionItemAssigneeDto.java
  src/main/java/com/yoyakso/comket/ai/dto/ActionItemContentDto.java
  src/main/java/com/yoyakso/comket/ai/dto/AiSummaryWithActionItemsResponse.java
  src/main/java/com/yoyakso/comket/ai/repository/AiActionItemsRepository.java
  src/main/java/com/yoyakso/comket/ai/repository/AiSummaryRepository.java
  src/main/java/com/yoyakso/comket/ai/service/AiService.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
Labels: 🏗️ Feature

#112 배포 #43
  src/main/java/com/yoyakso/comket/ai/controller/AiController.java
  src/main/java/com/yoyakso/comket/ai/dto/ActionItemAssigneeDto.java
  src/main/java/com/yoyakso/comket/ai/dto/ActionItemContentDto.java
  src/main/java/com/yoyakso/comket/ai/dto/AiSummaryWithActionItemsResponse.java
  src/main/java/com/yoyakso/comket/ai/repository/AiActionItemsRepository.java
  src/main/java/com/yoyakso/comket/ai/repository/AiSummaryRepository.java
  src/main/java/com/yoyakso/comket/ai/service/AiService.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
Labels: 🚀 Deploy

#113 AI 눈높이 요약 기능 개발
  src/main/java/com/yoyakso/comket/ai/controller/AiController.java
  src/main/java/com/yoyakso/comket/ai/dto/AiEyeLevelSummaryResponse.java
  src/main/java/com/yoyakso/comket/ai/service/AiService.java
  src/main/java/com/yoyakso/comket/ai/service/OpenAiClient.java
Labels: 🏗️ Feature
