Repository Yoyakso/COMKET_BE, pull requests merged in 2025-06, with the labels that each got.

#116 내 티켓 몰아보기 API 작업
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
Labels: 🏗️ Feature

#114 Alarm 관련 기본 기능 개발 사항
  .gitignore
  build.gradle
  src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmProjectCountResponse.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmTicketResponse.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmWorkspaceCountResponse.java
  src/main/java/com/yoyakso/comket/alarm/entity/ProjectAlarm.java
  src/main/java/com/yoyakso/comket/alarm/entity/TicketAlarm.java
  src/main/java/com/yoyakso/comket/alarm/enums/TicketAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/mapper/AlarmMapper.java
  src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/ticket/service/InternalTicketService.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/resources/application.yml
Labels: 🏗️ Feature

#117 배포 #45
  .gitignore
  build.gradle
  src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmProjectCountResponse.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmTicketResponse.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmWorkspaceCountResponse.java
  src/main/java/com/yoyakso/comket/alarm/entity/ProjectAlarm.java
  src/main/java/com/yoyakso/comket/alarm/entity/TicketAlarm.java
  src/main/java/com/yoyakso/comket/alarm/enums/TicketAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/mapper/AlarmMapper.java
  src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/InternalTicketService.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#118 리프레시 토큰 리팩터링
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
  src/main/java/com/yoyakso/comket/auth/dto/TokenReissueResponse.java
  src/main/java/com/yoyakso/comket/auth/service/AuthService.java
  src/main/java/com/yoyakso/comket/auth/service/RefreshTokenService.java
  src/main/java/com/yoyakso/comket/member/controller/MemberController.java
  src/main/java/com/yoyakso/comket/member/dto/MemberRegisterResponse.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/test/java/com/yoyakso/comket/auth/GoogleOAuth2ServiceTest.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
Labels: 🪛 Refactor

#119 Workspace, Member 정보 관리 수정
  src/main/java/com/yoyakso/comket/ai/service/AiService.java
  src/main/java/com/yoyakso/comket/auth/service/AuthService.java
  src/main/java/com/yoyakso/comket/member/controller/MemberController.java
  src/main/java/com/yoyakso/comket/member/dto/MemberInfoResponse.java
  src/main/java/com/yoyakso/comket/member/dto/MemberRegisterResponse.java
  src/main/java/com/yoyakso/comket/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/yoyakso/comket/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/yoyakso/comket/member/dto/response/MemberInfoResponse.java
  src/main/java/com/yoyakso/comket/member/dto/response/MemberRegisterResponse.java
  src/main/java/com/yoyakso/comket/member/entity/Member.java
  src/main/java/com/yoyakso/comket/member/mapper/MemberMapper.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/dto/request/WorkspaceMemberAuthorityUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/request/WorkspaceMemberCreateRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/request/WorkspaceMemberInfoUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/request/WorkspaceRegisterRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/request/WorkspaceUpdateRequest.java
  src/main/java/com/yoyakso/comket/workspace/dto/response/WorkspaceInfoResponse.java
  src/main/java/com/yoyakso/comket/workspace/dto/response/WorkspaceMemberInfoResponse.java
  src/main/java/com/yoyakso/comket/workspace/entity/Workspace.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/main/java/com/yoyakso/comket/workspaceMember/entity/WorkspaceMember.java
  src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
  src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java
Labels: 🏗️ Feature, 🪛 Refactor

#121 workspaceMember 자신 프로필 조회 API 추가
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
Labels: 🏗️ Feature

#124 배포 #48
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🚀 Deploy

#126 프론트 테섭 http 허용
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🛠️ Hot Fix

#127 배포 #49
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🚀 Deploy

#128 Fix: 구글 회원가입 시 멤버 에러 해결
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
Labels: 🛠️ Hot Fix

#129 배포 #50
  src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
  src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🚀 Deploy

#131 배포 #51
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketCreateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/request/TicketUpdateRequest.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/dto/response/TicketProjectInfoResponse.java
  src/main/java/com/yoyakso/comket/ticket/entity/Ticket.java
  src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
  src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🚀 Deploy

#132 프로젝트 OWNER, ADMIN 권한 병합
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
  src/main/java/com/yoyakso/comket/project/service/ProjectService.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
Labels: 🪛 Refactor

#134 비밀번호 재설정 메일 & 재설정 API 추가
  src/main/java/com/yoyakso/comket/email/controller/EmailController.java
  src/main/java/com/yoyakso/comket/email/dto/PasswordResetLinkRequest.java
  src/main/java/com/yoyakso/comket/email/dto/PasswordResetRequest.java
  src/main/java/com/yoyakso/comket/email/service/EmailService.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/resources/templates/EmailPasswordResetFormat.html
Labels: 🏗️ Feature

#135 배포 #53
  src/main/java/com/yoyakso/comket/email/controller/EmailController.java
  src/main/java/com/yoyakso/comket/email/dto/PasswordResetLinkRequest.java
  src/main/java/com/yoyakso/comket/email/dto/PasswordResetRequest.java
  src/main/java/com/yoyakso/comket/email/service/EmailService.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/resources/templates/EmailPasswordResetFormat.html
Labels: 🚀 Deploy

#136 Billling 관련 기능 추가
  src/main/java/com/yoyakso/comket/ComketApplication.java
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/controller/WorkspaceMemberHistoryController.java
  src/main/java/com/yoyakso/comket/billing/dto/request/BillingPlanChangeRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardRegisterRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardUpdateRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/response/BillingStatusResponse.java
  src/main/java/com/yoyakso/comket/billing/dto/response/CreditCardResponse.java
  src/main/java/com/yoyakso/comket/billing/entity/CreditCard.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceMemberHistory.java
  src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/repository/CreditCardRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceBillingRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceMemberHistoryRepository.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/billing/service/WorkspaceMemberHistoryService.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/billing/WorkspaceMemberHistoryServiceTest.java
Labels: 🏗️ Feature

#137 배포 #53
  src/main/java/com/yoyakso/comket/ComketApplication.java
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/controller/WorkspaceMemberHistoryController.java
  src/main/java/com/yoyakso/comket/billing/dto/request/BillingPlanChangeRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardRegisterRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardUpdateRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/response/BillingStatusResponse.java
  src/main/java/com/yoyakso/comket/billing/dto/response/CreditCardResponse.java
  src/main/java/com/yoyakso/comket/billing/entity/CreditCard.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceMemberHistory.java
  src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/repository/CreditCardRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceBillingRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceMemberHistoryRepository.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/billing/service/WorkspaceMemberHistoryService.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/billing/WorkspaceMemberHistoryServiceTest.java
Labels: 🚀 Deploy

#140 workspace-member-history 삭제 & workspace-billing으로 통일
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/controller/WorkspaceMemberHistoryController.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspacePlan.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceBillingRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceMemberHistoryRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspacePlanRepository.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/billing/service/WorkspaceMemberHistoryService.java
  src/main/java/com/yoyakso/comket/workspace/event/WorkspaceCreatedEvent.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/billing/WorkspaceMemberHistoryServiceTest.java
Labels: 🪛 Refactor

#142 fix : workspaceServiceTest 수정
  src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java
Labels: 🐞 Bug Fix

#141 배포 #55
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/controller/WorkspaceMemberHistoryController.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspacePlan.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceBillingRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspaceMemberHistoryRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/WorkspacePlanRepository.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/billing/service/WorkspaceMemberHistoryService.java
  src/main/java/com/yoyakso/comket/workspace/event/WorkspaceCreatedEvent.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/test/java/com/yoyakso/comket/billing/WorkspaceMemberHistoryServiceTest.java
  src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java
Labels: 🚀 Deploy

#145 멤버 탈퇴, 재가입 불가 이슈 로직 추가
  src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
  src/main/java/com/yoyakso/comket/auth/service/AuthService.java
  src/main/java/com/yoyakso/comket/member/entity/Member.java
  src/main/java/com/yoyakso/comket/member/repository/MemberRepository.java
  src/main/java/com/yoyakso/comket/member/service/MemberService.java
  src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
  src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
  src/test/java/com/yoyakso/comket/member/MemberServiceTest.java
Labels: 🏗️ Feature, 🪛 Refactor

#148 배포 #58
  src/main/java/com/yoyakso/comket/file/enums/FileCategory.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
  src/main/java/com/yoyakso/comket/thread/util/ResourceJsonUtil.java
  src/main/java/com/yoyakso/comket/thread/util/ThreadKafkaListenerManager.java
  src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java
Labels: 🚀 Deploy

#149 FCM 연동 추가
  .github/workflows/aws.yml
  .gitignore
  Dockerfile
  src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
  src/main/java/com/yoyakso/comket/alarm/controller/FCMController.java
  src/main/java/com/yoyakso/comket/alarm/dto/FCMTokenRequest.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/AlarmWorkspaceResponse.java
  src/main/java/com/yoyakso/comket/alarm/dto/response/ProjectAlarmResponse.java
  src/main/java/com/yoyakso/comket/alarm/entity/ProjectEventAlarm.java
  src/main/java/com/yoyakso/comket/alarm/entity/WorkspaceAlarm.java
  src/main/java/com/yoyakso/comket/alarm/enums/ProjectAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/enums/TicketAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/enums/WorkspaceAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/listener/ProjectAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/listener/TicketAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/listener/WorkspaceAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/mapper/AlarmMapper.java
  src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/alarm/service/FCMService.java
  src/main/java/com/yoyakso/comket/configuration/FirebaseConfig.java
  src/main/java/com/yoyakso/comket/project/event/ProjectInviteEvent.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/ticket/event/TicketAssignedEvent.java
  src/main/java/com/yoyakso/comket/ticket/event/TicketEvent.java
  src/main/java/com/yoyakso/comket/ticket/event/TicketStateChangedEvent.java
  src/main/java/com/yoyakso/comket/ticket/event/TicketUpdatedEvent.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
  src/main/java/com/yoyakso/comket/workspace/event/WorkspaceInviteEvent.java
  src/main/java/com/yoyakso/comket/workspace/event/WorkspaceRoleChangedEvent.java
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🏗️ Feature

#151 Billing 요금제 정책 변경 적용
  src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java
Labels: 🏗️ Update

#152 배포 #60
  src/main/java/com/yoyakso/comket/ai/entity/AiActionItem.java
  src/main/java/com/yoyakso/comket/ai/service/AiService.java
  src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java
  src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
  src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
  src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
  src/main/java/com/yoyakso/comket/thread/controller/ThreadMessageController.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDeleteRequestDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
  src/main/java/com/yoyakso/comket/thread/util/JwtHandshakeInterceptor.java
  src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
Labels: 🚀 Deploy

#154 프로필 이미지 카테고리 에러 수정
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
Labels: 🐞 Bug Fix

#155 배포 #61
  src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
Labels: 🚀 Deploy

#156 빌링 플랜 - memberCount 삭제
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspacePlan.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
Labels: 🐞 Bug Fix

#159 배포 #63
  src/main/java/com/yoyakso/comket/alarm/controller/FCMController.java
  src/main/java/com/yoyakso/comket/alarm/dto/FCMTestRequest.java
Labels: 🚀 Deploy

#160 내부 알람 로직 버그 수정
  src/main/java/com/yoyakso/comket/alarm/listener/TicketAlarmListener.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🐞 Bug Fix

#161 배포 #64
  src/main/java/com/yoyakso/comket/alarm/listener/TicketAlarmListener.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🚀 Deploy

#163 배포 #65
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🛠️ Hot Fix, 🚀 Deploy

#164 스레드 멘션 기능 추가
  src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
  src/main/java/com/yoyakso/comket/alarm/entity/ThreadAlarm.java
  src/main/java/com/yoyakso/comket/alarm/enums/ThreadAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/listener/ThreadAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/thread/controller/ThreadMessageController.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessageMention.java
  src/main/java/com/yoyakso/comket/thread/event/ThreadMentionedEvent.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
Labels: 🏗️ Feature

#165 베포 #66
  src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
  src/main/java/com/yoyakso/comket/alarm/entity/ThreadAlarm.java
  src/main/java/com/yoyakso/comket/alarm/enums/ThreadAlarmType.java
  src/main/java/com/yoyakso/comket/alarm/listener/ThreadAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/thread/controller/ThreadMessageController.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
  src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
  src/main/java/com/yoyakso/comket/thread/entity/ThreadMessageMention.java
  src/main/java/com/yoyakso/comket/thread/event/ThreadMentionedEvent.java
  src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
Labels: 🚀 Deploy

#168 멤버Id로 FCM 토큰 받도록 변경
  src/main/java/com/yoyakso/comket/alarm/entity/ThreadAlarm.java
  src/main/java/com/yoyakso/comket/alarm/listener/ThreadAlarmListener.java
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
Labels: 🐞 Bug Fix

#169 Feat/mention
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
Labels: 🐞 Bug Fix

#171 알림 클릭 시 스레드로 이동시키기 위한 데이터 추가, 스레드 수정, 답글의 경우에도 알림이 오도록 개선
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
Labels: 🏗️ Feature

#172 배포 #69
  src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
  src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
Labels: 🚀 Deploy

#173 Ticket 상세 조회시, project_id도 지원
  src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
  src/main/java/com/yoyakso/comket/ticket/service/TicketService.java
Labels: 🏗️ Update

#176 배포 #71
  .github/workflows/aws.yml
  build.gradle
  src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
  src/main/java/com/yoyakso/comket/billing/controller/PaymentController.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardRegisterRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardUpdateRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/request/PaymentVerifyRequest.java
  src/main/java/com/yoyakso/comket/billing/dto/response/CreditCardResponse.java
  src/main/java/com/yoyakso/comket/billing/entity/CreditCard.java
  src/main/java/com/yoyakso/comket/billing/entity/Payment.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
  src/main/java/com/yoyakso/comket/billing/entity/WorkspacePlan.java
  src/main/java/com/yoyakso/comket/billing/enums/PaymentStatus.java
  src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
  src/main/java/com/yoyakso/comket/billing/repository/CreditCardRepository.java
  src/main/java/com/yoyakso/comket/billing/repository/PaymentRepository.java
  src/main/java/com/yoyakso/comket/billing/service/BillingService.java
  src/main/java/com/yoyakso/comket/billing/service/PaymentService.java
  src/main/java/com/yoyakso/comket/configuration/iamportConfig.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#177 배포 #72
  src/main/java/com/yoyakso/comket/admin/controller/AdminController.java
  src/main/java/com/yoyakso/comket/admin/controller/AdminLoginController.java
  src/main/java/com/yoyakso/comket/admin/dto/response/FeatureUsageStatisticsResponse.java
  src/main/java/com/yoyakso/comket/admin/dto/response/OperationStatisticsResponse.java
  src/main/java/com/yoyakso/comket/admin/dto/response/UserBehaviorStatisticsResponse.java
  src/main/java/com/yoyakso/comket/admin/service/AdminStatisticsService.java
  src/main/java/com/yoyakso/comket/configuration/AdminAuthenticationEntryPoint.java
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
  src/main/java/com/yoyakso/comket/member/dto/response/MemberInfoResponse.java
  src/main/java/com/yoyakso/comket/member/mapper/MemberMapper.java
  src/main/resources/templates/admin-login.html
  src/main/resources/templates/admin-redirect.html
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/inquiries.html
  src/main/resources/templates/admin/inquiry-detail.html
  src/main/resources/templates/admin/statistics-feature-usage.html
  src/main/resources/templates/admin/statistics-operations.html
  src/main/resources/templates/admin/statistics-user-behavior.html
Labels: 🚀 Deploy

#178 Admin-Page용 허용 패턴 추가
  src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
Labels: 🐞 Bug Fix

#180 결제 검증 API 수정
  src/main/java/com/yoyakso/comket/billing/entity/Payment.java
  src/main/java/com/yoyakso/comket/billing/enums/PaymentStatus.java
Labels: 🐞 Bug Fix
